[project]
name = "omop_alchemy"
version="0.2"
description = "SQLAlchemy Models for OHDSI OMOP Common Data Model"
authors = [
  { name = "Georgie Kennedy", email = "georgie.kennedy@unsw.edu.au" }
]
license = "CC-BY-NC-SA-4.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "keyring>=25.7.0",
    "pandas>=2.3.3",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.3",
    "sqlalchemy>=2.0.45",
]

[dependency-groups]
dev = [
    "ipython>=9.8.0",
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "rich>=14.2.0",
    "ruff>=0.14.10",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["omop_alchemy*"]
